### ISSUE TITLE
Wrapper/CakePHP/V2/CacheDsn: Rename 'server' key to 'servers'

### ISSUE THREAD

**Issue by ojtibi** [AD7six/php-dsn#11]
According to the latest [CakePHP 2.x MemcacheEngine code](https://github.com/cakephp/cakephp/blob/2.7/lib/Cake/Cache/Engine/MemcachedEngine.php), the correct name of the key for configuring hosts should be `servers`, not `server`.

**Comment by AD7six** [comment]
Thanks for your interest here, as I no longer use or maintain this code I'll be archiving the project :)
