### ISSUE TITLE
Wrapper/CakePHP/V2/CacheDsn: Multiple hosts/servers as Array?

### ISSUE THREAD

**Issue by ojtibi** [AD7six/php-dsn#12]
I was wondering if it is possible for CacheDsn to return the `servers` (key name should be corrected as of issue #11) key as an array? CakePHP allows the MemcachedEngine to be configured to use multiple hosts, but only if this was set as an array.

I understand that the Dsn base class is using the native `parse_url()` to parse DSN strings (does not return individual URL components as arrays), which means my suggestion above might take more than a quick fix.

**Comment by AD7six** [comment]
Thanks for your interest here, as I no longer use or maintain this code I'll be archiving the project :)
