### ISSUE TITLE
Wrapper/CakePHP/V2/LogDsn: Value of 'mask' key incorrectly parsed as string

### ISSUE THREAD

**Issue by ojtibi** [AD7six/php-dsn#16]
Internally, CakePHP's `FileLog` class uses `chmod()` to change file attributes of the output file. According to the official [PHP documentation](http://php.net/chmod), `chmod()` uses a octal-formatted integer (not string, has leading zero) to specify the file mode.

Internally, `FileLog::write()` casts `$config['mask']` into a decimal integer, therefore a value of `'0775'` becomes `775`, which is probably incorrect according to the PHP documentation.

To correct this behavior, `LogDsn` should parse the `mask` key as an integer instead of a string. This will let `FileLog` correctly use the value of `mask` for `chmod()` and retain its literal value (for example, `0775` remains a proper octal integer).

**Comment by AD7six** [comment]
Thanks for your interest here, as I no longer use or maintain this code I'll be archiving the project :)
