### ISSUE TITLE
LogDsn allow console output (Cake V3)

### ISSUE THREAD

**Issue by pedro-stanaka** [AD7six/php-dsn#17]
Hello, is there a way to parse an url beginning with console:/// to allow the log to be written in the stderr? I'm trying to use this repo along with jozeGonzales/dotenv and couldn't find a way to do this in order to my application work in Heroku.

Cheers,

**Comment by AD7six** [comment]
Thanks for your interest here, as I no longer use or maintain this code I'll be archiving the project :)
