### ISSUE TITLE
Not parsing PDO dsn's

### ISSUE THREAD

**Issue by lcherone** [AD7six/php-dsn#18]
Im trying to parse a PDO dsn into its associative parts, but the database part is not correctly parsed.

```
$dsn = \AD7six\Dsn\DbDsn::parse('mysql:host=127.0.0.1;dbname=app'); 
print_r($dsn->toArray());
```

Result:

```
Array
(
    [engine] => mysql
    [port] => 3306
    [database] => host=127.0.0.1;dbname=app
)
```

**Comment by hron84** [comment]
Because this tool is not for parsng DSNs like PDO one, but could help generating PDO DSN based on URL-like syntax (consider JDBC URLs).

**Comment by AD7six** [comment]
Thanks for your interest here, as I no longer use or maintain this code I'll be archiving the project :)
